name: Deploy Hosting & Functions

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Deploy
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install -g firebase-tools
        cd functions
        npm install
    - name: Deploy
      run: |
        firebase deploy --only functions --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
